name: Gather stats for a single PR

on:
  repository_dispatch:
    types: [mathlib_ping]

permissions:
  contents: write

jobs:
  gather-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Careful: this script must NOT be run on a stubborn PR, otherwise this logic breaks.
        # (A stubborn PR would have a directory data/NUMBER-basic.)
        sparse-checkout: |
          data/${{ github.event.client_payload.pr_number }}
          scripts
        ref: master

    - name: "Run scripts/backfill.sh"
      id: "backfill"
      shell: bash -euo pipefail {0}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ls scripts
        ls data
        scripts/backfill.sh ${{ github.event.client_payload.pr_number }} 2>&1 | tee backfill.log

    - name: Commit changes
      id: "commit"
      env:
        NUMBER: ${{ github.event.client_payload.pr_number }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/$NUMBER
        git commit -m 'Update data/'

    - name: Push changes
      if: ${{ !cancelled() }} && steps.commit.outcome == 'success'
      run: |
        # XXX: this is not robust against other incoming changes
        git push
