name: Update PR metadata

on:
  schedule:
    - cron: '*/8 * * * *' # Runs every 8 minutes
  workflow_dispatch:       # Allows manual execution

permissions:
  contents: write

jobs:
  gather-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master

    - name: "Run gather_stats.sh"
      shell: bash -euo pipefail {0}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./gather_stats.sh 12 2>&1 | tee gather_stats.log  # Log output to gather_stats.log

    - name: "Update aggregate data file"
      if: ${{ !cancelled() }}
      run: |
        # Write files with aggregate PR data, to "processed_data/{all_pr,open_pr,assignment_}_data.json".
        python3 process.py

    - name: "Download .json files for all open PRs"
      id: "download-json"
      if: ${{ !cancelled() }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        bash ./dashboard.sh

    - name: "Check data integrity"
      if: ${{ !cancelled() }} && (steps.download-json.outcome == 'success')
      run: |
        python check_data_integrity.py

    - name: "(Re-)download missing or outdated PR data"
      if: ${{ !cancelled() }} && (steps.download-json.outcome == 'success')
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ./download_missing_outdated_PRs.sh

    - name: "Update aggregate data file (again)"
      if: ${{ !cancelled() }}
      run: |
        # Write files with aggregate PR data, to "processed_data/{all_pr,open_pr,assignment_}_data.json".
        python3 process.py

    - name: Commit changes
      if: ${{ !cancelled() }}
      id: "commit"
      run: |
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global user.name 'github-actions[bot]'
        git add data
        git add processed_data
        git add *.txt
        git commit -m 'Update data; redownload missing and outdated data; regenerate aggregate files'

    - name: Push changes
      if: ${{ !cancelled() }} && steps.commit.outcome == 'success'
      run: |
        # FIXME: make this more robust about incoming changes
        # The other workflow does not push to this branch, so this should be fine.
        git push

    - name: "Regenerate the dashboard webpages"
      if: ${{ !cancelled() }} && (steps.download-json.outcome == 'success')
      run: |
        python3 ./dashboard.py "all-open-PRs-1.json" "all-open-PRs-2.json"
        rm *.json

    - name: Commit and push changes
      if: ${{ !cancelled() }} && (steps.download-json.outcome == 'success')
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Temporarily rename the generated HTML files
        # to avoid a name collision with existing files on the gh-pages branch.
        mv index.html tmp.html
        mv on_the_queue.html tmp2.html
        mv review_dashboard.html tmp3.html
        mv maintainers_quick.html tmp4.html
        mv help_out.html tmp5.html
        mv triage.html tmp6.html
        git fetch --depth 1 origin gh-pages
        git checkout gh-pages
        mv tmp.html index.html
        mv tmp2.html on_the_queue.html
        mv tmp3.html review_dashboard.html
        mv tmp4.html maintainers_quick.html
        mv tmp5.html help_out.html
        mv tmp6.html triage.html
        git add index.html
        git add on_the_queue.html
        git add review_dashboard.html
        git add maintainers_quick.html
        git add help_out.html
        git add triage.html
        git checkout master -- style.css
        git commit -m "Update dashboard" -a || echo "No changes to commit"
        git push